# Case Study #1: Mental Health in Tech

## 1.0 Introduction
In this case study, we will analyze one data set compiled of survey responses. Input variables are a balance of variables that cover participant demographics and employment characteristics. 

The 27 survey questions are highlighted by their own input variables, each of which are discussed further in **2.2 Variables.**

## 2.0 Data Set

### 2.1 Source
This dataset is from a 2014 survey that measures attitudes towards mental health and frequency of mental health disorders in the tech workplace.

I located and downloaded the necessary files for this study from kaggle.com. The organization that originally uploaded this dataset to kaggle is Open Source Mental Illness (OSMI), a non-profit organization dedicated to raising awareness, educating, and providing resources to support mental wellness in the tech and open source communities.

[Link: https://www.kaggle.com/datasets/osmi/mental-health-in-tech-survey](https://www.kaggle.com/datasets/osmi/mental-health-in-tech-survey)

### 2.2 Variable Descriptions
| # | Variable | Description|
| --- | --- | --- |
| 1 | Timestamp | Date and time at which the survey response was submitted |
| 2 | Age | Respondent age |
| 3 | Gender | Respondent gender |
| 4 | Country | Respondent country of residence |
| 5 | state | If respondent lives in the United States, shows the abbreivation for their state of residence |
| 6 | self_employed | Is respondent self-employed? |
| 7 | family_history | Does respondent have a family history of mental illness? |
| 8 | treatment | Has respondent sought treatment for a mental health condition? |
| 9 | work_interfere | If respondent has mental health condition, do they feel that it interferes with their work? |
| 10 | no_employees | How many employees does the respondent's company/organization have? |
| 11 | remote_work | Does respondent work remotely (outside of office) at least 50% of the time? |
| 12 | tech_company | Is respondent's employer primarily a tech company/organization? |
| 13 | benefits | Does respondent's employer provide mental health benefits? |
| 14 | care_options | Does respondent know the options for mental health care that their employer provides? |
| 15 | wellness_program | Has respondent ever discussed mental health as part of an employee wellness program? |
| 16 | seek_help | Does respondent's employer provide resources to learn more about mental health issues and how to seek help? |
| 17 | anonymity | Is respondent's anonymity protected if they choose to take advantage of mental health or substance abuse treatment resources? |
| 18 | leave | How easy is it for respondent to take medical leave for a mental health condition? |
| 19 | mental_health_consequence | Does respondent think that discussing a mental health issue with their employer would have negative consequences? |
| 20 | phys_health_consequence | Does respondent think that discussing a physical health issue with their employer would have negative consequences? |
| 21 | coworkers | Would respondent be willing to discuss a mental health issue with their coworkers? |
| 22 | supervisor | Would respondent be willing to discuss a mental health issue with their direct supervisor(s)? |
| 23 | mental_health_interview | Would respondent bring up a mental health issue with a potential employer in an interview? |
| 24 | phys_health_interview | Would respondent bring up a physical health issue with a potential employer in an interview? |
| 25 | mental_vs_physical | Does respondent feel that their employer takes mental health as seriously as physical health? |
| 26 | obs_consequence | Has the respondent ever heard of or observed negative consequences for coworkers with mental health conditions in their workplace? |
| 27 | comments | Any additional notes or comments. |

## 3.0 Objectives
Based on the data set provided, I would like to analyze whether there is a relation between respondent's having a family history of mental health and their openness to talking about mental health in their tech work places. I would also like to dig into whether there is any distinctions in this relationship based on respondent's country of origin. 
### 3.1 Inspiration Questions
The Kaggle uploader and datset collector, OSMI, highlighted the following questions as potential areas of baseline analysis.
1. How does the frequency of mental health illness and attitudes towards mental health vary by geographic location?
2. What are the strongest predictors of mental health illness or certain attitudes towards mental health in the workplace?
### 3.2 Guiding Questions
Based on the dataset, I have come up with the following questions in order to provide some more specific structure to my analysis.
1. Are respondents with a family history of mental illness more or less likely to discuss mental health issues with their coworkers and supervisors?
2. Which countries show a gap between employee's awareness of mental health resources and their likelihood of seeking out treatment?

## 4.0 Assessing Data

### 4.1 Context and Relevance
The data I used for this case study was sourced by: 

a. Where is the data set coming from?

b. How is the data sourced?

c. How is the data collected?

d. How often is the data updated?

e. Are there any potential biases in the data?

Next, let's take a deeper look at our data.

### 4.2 Data Quality

In [ ]:
# import libraries and load csv
import pandas as pd
import numpy as np

survey = pd.read_csv(r'survey.csv')

In [2]:
# check for missing values
survey.isnull().sum()

Timestamp                       0
Age                             0
Gender                          0
Country                         0
state                         515
self_employed                  18
family_history                  0
treatment                       0
work_interfere                264
no_employees                    0
remote_work                     0
tech_company                    0
benefits                        0
care_options                    0
wellness_program                0
seek_help                       0
anonymity                       0
leave                           0
mental_health_consequence       0
phys_health_consequence         0
coworkers                       0
supervisor                      0
mental_health_interview         0
phys_health_interview           0
mental_vs_physical              0
obs_consequence                 0
comments                     1095
dtype: int64

In [3]:
# check for duplicate rows in survey dataset
survey.duplicated().sum()

np.int64(1)

### 4.3 Data Structure and Types

In [4]:
# number of samples and variables in survey dataset
survey.shape

(1259, 27)

In [5]:
# check column types & missing values
survey.info()

<class 'pandas.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Timestamp                  1259 non-null   str
 1   Age                        1259 non-null   int64
 2   Gender                     1259 non-null   str
 3   Country                    1259 non-null   str
 4   state                      744 non-null    str
 5   self_employed              1241 non-null   str
 6   family_history             1259 non-null   str
 7   treatment                  1259 non-null   str
 8   work_interfere             995 non-null    str
 9   no_employees               1259 non-null   str
 10  remote_work                1259 non-null   str
 11  tech_company               1259 non-null   str
 12  benefits                   1259 non-null   str
 13  care_options               1259 non-null   str
 14  wellness_program           1259 non-null   str
 15  seek_help                  1259 non-null   str
 16  anonymity                  1259 non-null   str
 17  leave                      1259 non-null   str
 18  mental_health_consequence  1259 non-null   str
 19  phys_health_consequence    1259 non-null   str
 20  coworkers                  1259 non-null   str
 21  supervisor                 1259 non-null   str
 22  mental_health_interview    1259 non-null   str
 23  phys_health_interview      1259 non-null   str
 24  mental_vs_physical         1259 non-null   str
 25  obs_consequence            1259 non-null   str
 26  comments                   164 non-null    str
dtypes: int64(1), str(26)
memory usage: 265.7 KB

### 4.4 Distribution

In [6]:
# statistical summary for numerical columns
pd.set_option('display.float_format', '{:.2f}'.format)
survey.describe()

                 Age
count        1259.00
mean     79428148.31
std    2818299442.98
min         -1726.00
25%            27.00
50%            31.00
75%            36.00
max   99999999999.00

## 5.0 Data Cleaning

### 5.1 Dedupe

In [7]:
# drop duplicates
survey = survey.drop_duplicates()
survey

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,8/27/2014 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,8/27/2014 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,8/27/2014 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,8/27/2014 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,8/27/2014 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,9/12/2015 11:17,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Somewhat easy,No,No,Some of them,Some of them,No,No,Don't know,No,NaN
1255,9/26/2015 1:07,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Somewhat difficult,No,No,Some of them,Yes,No,No,Yes,No,NaN
1256,11/7/2015 12:36,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,Somewhat difficult,Yes,Yes,No,No,No,No,No,No,NaN
1257,11/30/2015 21:25,46,f,United States,NC,No,No,No,NaN,100-500,...,Don't know,Yes,No,No,No,No,No,No,No,NaN
1258,2/1/2016 23:04,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,No,No,Don't know,No,NaN

### 5.2 Remove Extraneous Columns

### 5.2 Column Transformations

In [8]:
# transforming timestamp column
survey[["Date","Time"]] = survey["Timestamp"].str.split(" ", expand=True)
survey = survey.drop(columns = ["Time"])
survey[["Month","Day","Year"]] = survey["Date"].str.split("/",n=2,expand=True)
survey

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments,Date,Month,Day,Year
0,8/27/2014 11:29,37,Female,United States,IL,NaN,No,Yes,Often,25-Jun,...,Yes,No,Maybe,Yes,No,NaN,8/27/2014,8,27,2014
1,8/27/2014 11:29,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,No,No,No,Don't know,No,NaN,8/27/2014,8,27,2014
2,8/27/2014 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,25-Jun,...,Yes,Yes,Yes,No,No,NaN,8/27/2014,8,27,2014
3,8/27/2014 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,No,Maybe,Maybe,No,Yes,NaN,8/27/2014,8,27,2014
4,8/27/2014 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Yes,Yes,Yes,Don't know,No,NaN,8/27/2014,8,27,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,9/12/2015 11:17,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,Some of them,No,No,Don't know,No,NaN,9/12/2015,9,12,2015
1255,9/26/2015 1:07,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,Yes,No,No,Yes,No,NaN,9/26/2015,9,26,2015
1256,11/7/2015 12:36,34,male,United States,CA,No,Yes,Yes,Sometimes,More than 1000,...,No,No,No,No,No,NaN,11/7/2015,11,7,2015
1257,11/30/2015 21:25,46,f,United States,NC,No,No,No,NaN,100-500,...,No,No,No,No,No,NaN,11/30/2015,11,30,2015
1258,2/1/2016 23:04,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,No,No,No,Don't know,No,NaN,2/1/2016,2,1,2016

In [9]:
# transform gender column responses

In [10]:
# transform no_employees column responses
survey["no_employees"] = survey["no_employees"].str.replace("25-Jun","6-25")
survey["no_employees"] = survey["no_employees"].str.replace("5-Jan", "1-5")
survey["no_employees"] = survey["no_employees"].str.replace("More than 1000", "1000-5000")
survey[["min_employees","max_employees"]] = survey["no_employees"].str.split("-",expand=True)
survey

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,phys_health_interview,mental_vs_physical,obs_consequence,comments,Date,Month,Day,Year,min_employees,max_employees
0,8/27/2014 11:29,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Maybe,Yes,No,NaN,8/27/2014,8,27,2014,6,25
1,8/27/2014 11:29,44,M,United States,IN,NaN,No,No,Rarely,1000-5000,...,No,Don't know,No,NaN,8/27/2014,8,27,2014,1000,5000
2,8/27/2014 11:29,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Yes,No,No,NaN,8/27/2014,8,27,2014,6,25
3,8/27/2014 11:29,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Maybe,No,Yes,NaN,8/27/2014,8,27,2014,26,100
4,8/27/2014 11:30,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Yes,Don't know,No,NaN,8/27/2014,8,27,2014,100,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,9/12/2015 11:17,26,male,United Kingdom,NaN,No,No,Yes,NaN,26-100,...,No,Don't know,No,NaN,9/12/2015,9,12,2015,26,100
1255,9/26/2015 1:07,32,Male,United States,IL,No,Yes,Yes,Often,26-100,...,No,Yes,No,NaN,9/26/2015,9,26,2015,26,100
1256,11/7/2015 12:36,34,male,United States,CA,No,Yes,Yes,Sometimes,1000-5000,...,No,No,No,NaN,11/7/2015,11,7,2015,1000,5000
1257,11/30/2015 21:25,46,f,United States,NC,No,No,No,NaN,100-500,...,No,No,No,NaN,11/30/2015,11,30,2015,100,500
1258,2/1/2016 23:04,25,Male,United States,IL,No,Yes,Yes,Sometimes,26-100,...,No,Don't know,No,NaN,2/1/2016,2,1,2016,26,100

### 5.3 Remove Extraneous Columns

In [11]:
# drop comments and state column
survey = survey.drop(columns = ["comments", "state","Date","Month","Day"])
survey

,Timestamp,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,...,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,Year,min_employees,max_employees
0,8/27/2014 11:29,37,Female,United States,NaN,No,Yes,Often,6-25,No,...,No,Some of them,Yes,No,Maybe,Yes,No,2014,6,25
1,8/27/2014 11:29,44,M,United States,NaN,No,No,Rarely,1000-5000,No,...,No,No,No,No,No,Don't know,No,2014,1000,5000
2,8/27/2014 11:29,32,Male,Canada,NaN,No,No,Rarely,6-25,No,...,No,Yes,Yes,Yes,Yes,No,No,2014,6,25
3,8/27/2014 11:29,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,...,Yes,Some of them,No,Maybe,Maybe,No,Yes,2014,26,100
4,8/27/2014 11:30,31,Male,United States,NaN,No,No,Never,100-500,Yes,...,No,Some of them,Yes,Yes,Yes,Don't know,No,2014,100,500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1254,9/12/2015 11:17,26,male,United Kingdom,No,No,Yes,NaN,26-100,No,...,No,Some of them,Some of them,No,No,Don't know,No,2015,26,100
1255,9/26/2015 1:07,32,Male,United States,No,Yes,Yes,Often,26-100,Yes,...,No,Some of them,Yes,No,No,Yes,No,2015,26,100
1256,11/7/2015 12:36,34,male,United States,No,Yes,Yes,Sometimes,1000-5000,No,...,Yes,No,No,No,No,No,No,2015,1000,5000
1257,11/30/2015 21:25,46,f,United States,No,No,No,NaN,100-500,Yes,...,No,No,No,No,No,No,No,2015,100,500
1258,2/1/2016 23:04,25,Male,United States,No,Yes,Yes,Sometimes,26-100,No,...,No,Some of them,No,No,No,Don't know,No,2016,26,100

### 5.4 Handle Invalid Values

In [12]:
# move date